### ISSUE TITLE
pip fails to install (ModuleNotFoundError: No module named 'Cython')

### ISSUE THREAD

**Issue by certik** [rjfarmer/gfort2py#11]
Steps to reproduce:
```
$ conda create -n gfort python
$ conda activate gfort
$ pip install gfort2py
Collecting gfort2py
  Downloading https://files.pythonhosted.org/packages/71/50/6f27804fc3642ccc132c13ff03d999c7cde957e1aa04102b58ec0140234f/gfort2py-1.1.2.tar.gz (97kB)
    100% |████████████████████████████████| 102kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c0ux4c0l/gfort2py/setup.py", line 7, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-c0ux4c0l/gfort2py/
```

**Comment by certik** [comment]
To fix this, do:
```
$ conda install cython numpy
```

**Comment by rjfarmer** [comment]
Right you need to get pip to install the files from the requirements.txt file:

    pip install -r requirements.txt

**Comment by certik** [comment]
I see. I thought that `pip install` somehow does this automatically. I am pretty sure that's how it works for other packages.
