### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by certik** [rjfarmer/gfort2py#12]
```
$ cat a.py 
from gfort2py import fFort

x = fFort("./libhfsolver.so", "utils.mod")
$ python a.py 
Traceback (most recent call last):
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/gfort2py.py", line 44, in _load_data
    f = open(self._fpy, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'utils.fpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 3, in <module>
    x = fFort("./libhfsolver.so", "utils.mod")
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/gfort2py.py", line 38, in __init__
    self._load_data(ffile, rerun)
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/gfort2py.py", line 49, in _load_data
    pm.run(ffile, save=True)
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/parseMod/parseMod.py", line 57, in run
    x.processData()
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/parseMod/parseModCommon.py", line 54, in processData
    self.parseAllSymbols()
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/parseMod/parseModCommon.py", line 185, in parseAllSymbols
    x = self.parseSymbol(i)
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/parseMod/parseModCommon.py", line 238, in parseSymbol
    r['proc'] = self.parseProc(info)
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/parseMod/parseModCommon.py", line 321, in parseProc
    res['ret'] = self.parseVar(info)
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/parseMod/parseModCommon.py", line 271, in parseVar
    res['length'] = self.getStrLen(info)
  File "/home/ondrej/miniconda3/envs/gfort/lib/python3.7/site-packages/gfort2py/parseMod/parseModCommon.py", line 467, in getStrLen
    return int(y)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by certik** [comment]
Here is a smaller example that reproduces the bug:
```fortran
module tester
implicit none

contains

pure integer function str_int_len(i) result(sz)
! Returns the length of the string representation of 'i'
integer, intent(in) :: i
integer, parameter :: MAX_STR = 100
character(MAX_STR) :: s
! If 's' is too short (MAX_STR too small), Fortran will abort with:
! "Fortran runtime error: End of record"
write(s, '(i0)') i
sz = len_trim(s)
end function

pure function str_int(i) result(s)
! Converts integer "i" to string
integer, intent(in) :: i
character(len=str_int_len(i)) :: s
write(s, '(i0)') i
end function

end module
```

**Comment by rjfarmer** [comment]
What version of gfort2py/gfortran are you using?

For me i get the right size, the problem comes when trying to call the function. It seems when using the result() keyword gfortran8 wants the function we actually call to look like this:

    str_int(char *s, int len(s), int i) 

While normally we assume the len of a string argument ends up at the end of the argument list, not in the middle.

I'll need to think what to do. My guess is you have a < gfortran8 so things manifest as a different error, which will also need thinking about

**Comment by certik** [comment]
I use gfortran 7.3.0.
