### ISSUE TITLE
pip install fails due to absence of Cython

### ISSUE THREAD

**Issue by HugoMVale** [rjfarmer/gfort2py#34]
I am unable to pip install `gfort2py` and get the error below.
This is odd, because I do have Cython.
It is also intriguing because the last commit message of `pyproject.toml` is "remove last bits of cython".
Any hints on how to solve the issue?

```shell
(.venv) PS C:\Code\fortran-in-python\src> pip list
Package        Version
-------------- -------
autopep8       2.0.2
ConfigArgParse 1.5.3
Cython         0.29.35
f90wrap        0.2.13
flake8         6.0.0
fprettify      0.3.7
llvmlite       0.40.0
mccabe         0.7.0
numba          0.57.0
numpy          1.24.3
pip            23.1.2
pycodestyle    2.10.0
pyflakes       3.0.1
setuptools     65.5.0
(.venv) PS C:\Code\fortran-in-python\src> pip install gfort2py
Collecting gfort2py
  Using cached gfort2py-1.1.7.tar.gz (100 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Code\fortran-in-python\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Code\fortran-in-python\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Code\fortran-in-python\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel        
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hugom\AppData\Local\Temp\pip-build-env-zdq9znd6\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel     
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hugom\AppData\Local\Temp\pip-build-env-zdq9znd6\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\hugom\AppData\Local\Temp\pip-build-env-zdq9znd6\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hugom\AppData\Local\Temp\pip-build-env-zdq9znd6\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by rjfarmer** [comment]
The version on pypi still requires cython. Though I don't know why it can't find it.

You could try installing from source, which does not require cython.

**Comment by HugoMVale** [comment]
I tried installing the gfort2py from pypi using another computer and got the exact same error.  So, I would dare saying that, at least for Windows machines, the latest version in pypi is very likely broken. Maybe you want to fix that.
Installing the current version in the github repo works fine.
